name: 'Linear release sync'
description: 'Add release on linear tickets in merged PRs since last release'
author: 'Rayon'


inputs:
  token:
    description: 'Github token'
    required: false
    default: ${{ github.token }}
  linearApiKey:
    description: 'Linear API key'
    required: true
  releaseLabel:
    description: 'Release label pu in linear'
    required: true
  maxPrLength:
    description: 'Maximum number of PRs fetch with the API'
    required: false
    default: '100'
  baseBranch:
    default: 'dev'
    required: false
    description: 'Main branch where PRs are merged'
  ticketPrefix:
    default: 'RAY'
    required: false
    description: 'Ticket prefix (can be a regex)'
  stateId:
    default: '2dd3bad8-0d14-4708-84ff-a2903d36857a'
    required: false
    description: 'If you want to update your ticket state'



runs:
  using: node20
  main: dist/index.js
