name: 'Linear release sync'
description: 'Add release label on linear tickets found in PRs merged in base branch since last release'
author: 'Rayon'


# Define your inputs here.
inputs:
  token:
    description: 'Github token'
    required: true
  linearApiKey:
    description: 'Linear API key'
    required: true
  releaseLabel:
    description: 'Release label pu in linear'
    required: true
  maxPrLength:
    description: 'Maximum number of PRs fetch with the API'
    required: false
    default: '100'
  baseBranch:
    default: 'dev'
    required: false
    description: 'Main branch where PRs are merged'



runs:
  using: node20
  main: dist/index.js
